#include "JIT_OpCodes.h"


static char * opcodes_str[512] = { 0 };

static int is_init = 0;

#define CH(op)op

static void init_str_opcodes()
{
	opcodes_str[JIT_NOP] = CH("JIT_NOP");
	opcodes_str[JIT_RETURN] = CH("JIT_RETURN");
	opcodes_str[ JIT_LOAD_I32] = CH("JIT_LOAD_I32");
	opcodes_str[ JIT_BRANCH] = CH("JIT_BRANCH");
	opcodes_str[ JIT_LOAD_STRING] = CH("JIT_LOAD_STRING");
	opcodes_str[ JIT_CALLVIRT_O] = CH("JIT_CALLVIRT_O");
	opcodes_str[ JIT_CALL_NATIVE] = CH("JIT_CALL_NATIVE");
	opcodes_str[ JIT_CALL_O] = CH("JIT_CALL_O");
	opcodes_str[ JIT_NEWOBJECT] = CH("JIT_NEWOBJECT");
	opcodes_str[ JIT_LOAD_PARAMLOCAL_ADDR] = CH("JIT_LOAD_PARAMLOCAL_ADDR");
	opcodes_str[ JIT_CALL_PTR] = CH("JIT_CALL_PTR");
	opcodes_str[ JIT_BOX_CALLVIRT] = CH("JIT_BOX_CALLVIRT");
	opcodes_str[ JIT_INIT_VALUETYPE] = CH("JIT_INIT_VALUETYPE");
	opcodes_str[ JIT_NEW_VECTOR] = CH("JIT_NEW_VECTOR");
	opcodes_str[ JIT_NEWOBJECT_VALUETYPE] = CH("");
	opcodes_str[ JIT_IS_INSTANCE] = CH("JIT_IS_INSTANCE");
	opcodes_str[ JIT_LOAD_NULL] = CH("JIT_LOAD_NULL");
	opcodes_str[ JIT_UNBOX2VALUETYPE] = CH("JIT_UNBOX2VALUETYPE");
	opcodes_str[ JIT_UNBOX2OBJECT] = CH("JIT_UNBOX2OBJECT");
	opcodes_str[ JIT_LOAD_FIELD_ADDR] = CH("JIT_LOAD_FIELD_ADDR");
	opcodes_str[JIT_DUP_GENERAL] = CH("JIT_DUP_GENERAL");
	opcodes_str[JIT_POP] = CH("JIT_POP");
	opcodes_str[JIT_STORE_OBJECT_VALUETYPE] = CH("JIT_STORE_OBJECT_VALUETYPE");
	opcodes_str[JIT_DEREF_CALLVIRT] = CH("JIT_DEREF_CALLVIRT");
	opcodes_str[JIT_STORE_ELEMENT] = CH("JIT_STORE_ELEMENT");
	opcodes_str[JIT_LEAVE] = CH("JIT_LEAVE");
	opcodes_str[JIT_END_FINALLY] = CH("JIT_END_FINALLY");
	opcodes_str[JIT_THROW] = CH("JIT_THROW");
	opcodes_str[JIT_RETHROW] = CH("JIT_RETHROW");
	opcodes_str[JIT_LOADOBJECT] = CH("JIT_LOADOBJECT");
	opcodes_str[JIT_LOAD_VECTOR_LEN] = CH("JIT_LOAD_VECTOR_LEN");
	opcodes_str[JIT_SWITCH] = CH("JIT_SWITCH");
	opcodes_str[JIT_LOAD_ELEMENT_ADDR] = CH("JIT_LOAD_ELEMENT_ADDR");
	opcodes_str[JIT_CALL_INTERFACE] = CH("JIT_CALL_INTERFACE");
	opcodes_str[JIT_CAST_CLASS] = CH("JIT_CAST_CLASS");
	opcodes_str[JIT_LOAD_ELEMENT] = CH("");
	opcodes_str[JIT_LOADFIELD_VALUETYPE] = CH("JIT_LOADFIELD_VALUETYPE");
	opcodes_str[JIT_LOADFIELD] = CH("JIT_LOADFIELD");
	opcodes_str[JIT_LOADFUNCTION] = CH("JIT_LOADFUNCTION");
	opcodes_str[JIT_INVOKE_DELEGATE] = CH("JIT_INVOKE_DELEGATE");
	opcodes_str[JIT_CALL_PINVOKE] = CH("JIT_CALL_PINVOKE");
	opcodes_str[JIT_LOAD_I64] = CH("JIT_LOAD_I64");
	opcodes_str[JIT_INIT_OBJECT] = CH("JIT_INIT_OBJECT");
	opcodes_str[JIT_DUP_4] = CH("JIT_DUP_4");
	opcodes_str[JIT_DUP_8] = CH("JIT_DUP_8");
	opcodes_str[JIT_LOADSTATICFIELDADDRESS_CHECKTYPEINIT] = CH("JIT_LOADSTATICFIELDADDRESS_CHECKTYPEINIT");
	opcodes_str[JIT_POP_4] = CH("JIT_POP_4");
	opcodes_str[JIT_LOAD_F32] = CH("JIT_LOAD_F32");


	opcodes_str[JIT_LOADPARAMLOCAL_TYPEID] = CH("JIT_LOADPARAMLOCAL_TYPEID");
	opcodes_str[JIT_LOADPARAMLOCAL_INT64] = CH("JIT_LOADPARAMLOCAL_INT64");
	opcodes_str[JIT_LOADPARAMLOCAL_INT32] = CH("JIT_LOADPARAMLOCAL_INT32");
	opcodes_str[JIT_LOADPARAMLOCAL_INTNATIVE] = CH("JIT_LOADPARAMLOCAL_INTNATIVE");
	//opcodes_str[JIT_LOADPARAMLOCAL_F] = CH("JIT_LOADPARAMLOCAL_F");
	opcodes_str[JIT_LOADPARAMLOCAL_F32] = CH("JIT_LOADPARAMLOCAL_F32");
	opcodes_str[JIT_LOADPARAMLOCAL_PTR] = CH("JIT_LOADPARAMLOCAL_PTR");
	opcodes_str[JIT_LOADPARAMLOCAL_O] = CH("JIT_LOADPARAMLOCAL_O");
	//opcodes_str[JIT_LOADPARAMLOCAL_TRANSPTR] = CH("JIT_LOADPARAMLOCAL_TRANSPTR");
	opcodes_str[JIT_LOADPARAMLOCAL_F64] = CH("JIT_LOADPARAMLOCAL_F64");
	opcodes_str[JIT_LOADPARAMLOCAL_VALUETYPE] = CH("JIT_LOADPARAMLOCAL_VALUETYPE");
	opcodes_str[JIT_STOREPARAMLOCAL_TYPEID] = CH("JIT_STOREPARAMLOCAL_TYPEID");
	opcodes_str[JIT_STOREPARAMLOCAL_INT64] = CH("JIT_STOREPARAMLOCAL_INT64");
	opcodes_str[JIT_STOREPARAMLOCAL_INT32] = CH("JIT_STOREPARAMLOCAL_INT32");
	opcodes_str[JIT_STOREPARAMLOCAL_INTNATIVE] = CH("JIT_STOREPARAMLOCAL_INTNATIVE");
	//opcodes_str[JIT_STOREPARAMLOCAL_F] = CH("JIT_STOREPARAMLOCAL_F");
	opcodes_str[JIT_STOREPARAMLOCAL_F32] = CH("JIT_STOREPARAMLOCAL_F32");
	opcodes_str[JIT_STOREPARAMLOCAL_PTR] = CH("JIT_STOREPARAMLOCAL_PTR");
	opcodes_str[JIT_STOREPARAMLOCAL_O] = CH("JIT_STOREPARAMLOCAL_O");
	//opcodes_str[JIT_STOREPARAMLOCAL_TRANSPTR] = CH("JIT_STOREPARAMLOCAL_TRANSPTR");
	opcodes_str[JIT_STOREPARAMLOCAL_F64] = CH("JIT_STOREPARAMLOCAL_F64");
	opcodes_str[JIT_STOREPARAMLOCAL_VALUETYPE] = CH("JIT_STOREPARAMLOCAL_VALUETYPE");
	opcodes_str[JIT_STOREFIELD_TYPEID] = CH("JIT_STOREFIELD_TYPEID");
	opcodes_str[JIT_STOREFIELD_INT64] = CH("JIT_STOREFIELD_INT64");
	opcodes_str[JIT_STOREFIELD_INT32] = CH("JIT_STOREFIELD_INT32");
	opcodes_str[JIT_STOREFIELD_INTNATIVE] = CH("JIT_STOREFIELD_INTNATIVE");
	//opcodes_str[JIT_STOREFIELD_F] = CH("JIT_STOREFIELD_F");
	opcodes_str[JIT_STOREFIELD_F32] = CH("JIT_STOREFIELD_F32");
	opcodes_str[JIT_STOREFIELD_PTR] = CH("JIT_STOREFIELD_PTR");
	opcodes_str[JIT_STOREFIELD_O] = CH("JIT_STOREFIELD_O");
	//opcodes_str[JIT_STOREFIELD_TRANSPTR] = CH("JIT_STOREFIELD_TRANSPTR");
	opcodes_str[JIT_STOREFIELD_F64] = CH("JIT_STOREFIELD_F64");
	opcodes_str[JIT_STOREFIELD_VALUETYPE] = CH("JIT_STOREFIELD_VALUETYPE");

	opcodes_str[JIT_LOADSTATICFIELD_CHECKTYPEINIT_TYPEID] = CH("JIT_LOADSTATICFIELD_CHECKTYPEINIT_TYPEID");
	opcodes_str[JIT_LOADSTATICFIELD_CHECKTYPEINIT_INT64] = CH("JIT_LOADSTATICFIELD_CHECKTYPEINIT_INT64");
	opcodes_str[JIT_LOADSTATICFIELD_CHECKTYPEINIT_INT32] = CH("JIT_LOADSTATICFIELD_CHECKTYPEINIT_INT32");
	opcodes_str[JIT_LOADSTATICFIELD_CHECKTYPEINIT_INTNATIVE] = CH("JIT_LOADSTATICFIELD_CHECKTYPEINIT_INTNATIVE");
	//opcodes_str[JIT_LOADSTATICFIELD_CHECKTYPEINIT_F] = CH("JIT_LOADSTATICFIELD_CHECKTYPEINIT_F");
	opcodes_str[JIT_LOADSTATICFIELD_CHECKTYPEINIT_F32] = CH("JIT_LOADSTATICFIELD_CHECKTYPEINIT_F32");
	opcodes_str[JIT_LOADSTATICFIELD_CHECKTYPEINIT_PTR] = CH("JIT_LOADSTATICFIELD_CHECKTYPEINIT_PTR");
	opcodes_str[JIT_LOADSTATICFIELD_CHECKTYPEINIT_O] = CH("JIT_LOADSTATICFIELD_CHECKTYPEINIT_O");
	//opcodes_str[JIT_LOADSTATICFIELD_CHECKTYPEINIT_TRANSPTR] = CH("");
	opcodes_str[JIT_LOADSTATICFIELD_CHECKTYPEINIT_F64] = CH("JIT_LOADSTATICFIELD_CHECKTYPEINIT_F64");
	opcodes_str[JIT_LOADSTATICFIELD_CHECKTYPEINIT_VALUETYPE] = CH("JIT_LOADSTATICFIELD_CHECKTYPEINIT_VALUETYPE");

	opcodes_str[JIT_LOADSTATICFIELD_TYPEID] = CH("JIT_LOADSTATICFIELD_TYPEID");
	opcodes_str[JIT_LOADSTATICFIELD_INT64] = CH("JIT_LOADSTATICFIELD_INT64");
	opcodes_str[JIT_LOADSTATICFIELD_INT32] = CH("JIT_LOADSTATICFIELD_INT32");
	opcodes_str[JIT_LOADSTATICFIELD_INTNATIVE] = CH("JIT_LOADSTATICFIELD_INTNATIVE");
	//opcodes_str[JIT_LOADSTATICFIELD_F] = CH("JIT_LOADSTATICFIELD_F");
	opcodes_str[JIT_LOADSTATICFIELD_F32] = CH("JIT_LOADSTATICFIELD_F32");
	opcodes_str[JIT_LOADSTATICFIELD_PTR] = CH("JIT_LOADSTATICFIELD_PTR");
	opcodes_str[JIT_LOADSTATICFIELD_O] = CH("JIT_LOADSTATICFIELD_O");
	//opcodes_str[JIT_LOADSTATICFIELD_TRANSPTR] = CH("JIT_LOADSTATICFIELD_TRANSPTR");
	opcodes_str[JIT_LOADSTATICFIELD_F64] = CH("JIT_LOADSTATICFIELD_F64");
	opcodes_str[JIT_LOADSTATICFIELD_VALUEPTYE] = CH("JIT_LOADSTATICFIELD_VALUEPTYE");

	opcodes_str[JIT_STORESTATICFIELD_TYPEID] = CH("JIT_STORESTATICFIELD_TYPEID");
	opcodes_str[JIT_STORESTATICFIELD_INT64] = CH("JIT_STORESTATICFIELD_INT64");
	opcodes_str[JIT_STORESTATICFIELD_INT32] = CH("JIT_STORESTATICFIELD_INT32");
	opcodes_str[JIT_STORESTATICFIELD_INTNATIVE] = CH("JIT_STORESTATICFIELD_INTNATIVE");
	//opcodes_str[JIT_STORESTATICFIELD_F] = CH("JIT_STORESTATICFIELD_F");
	opcodes_str[JIT_STORESTATICFIELD_F32] = CH("JIT_STORESTATICFIELD_F32");
	opcodes_str[JIT_STORESTATICFIELD_F64] = CH("JIT_STORESTATICFIELD_F64");
	opcodes_str[JIT_STORESTATICFIELD_PTR] = CH("JIT_STORESTATICFIELD_PTR");
	opcodes_str[JIT_STORESTATICFIELD_O] = CH("JIT_STORESTATICFIELD_O");
	//opcodes_str[JIT_STORESTATICFIELD_TRANSPTR] = CH("JIT_STORESTATICFIELD_TRANSPTR");
	opcodes_str[JIT_STORESTATICFIELD_VALUETYPE] = CH("JIT_STORESTATICFIELD_VALUETYPE");

	opcodes_str[JIT_BOX_TYPEID] = CH("JIT_BOX_TYPEID");
	opcodes_str[JIT_BOX_INT64] = CH("JIT_BOX_INT64");
	opcodes_str[JIT_BOX_INT32] = CH("JIT_BOX_INT32");
	opcodes_str[JIT_BOX_INTNATIVE] = CH("JIT_BOX_INTNATIVE");
	//opcodes_str[JIT_BOX_F] = CH("JIT_BOX_F");
	opcodes_str[JIT_BOX_F32] = CH("JIT_BOX_F32");
	opcodes_str[JIT_BOX_PTR] = CH("JIT_BOX_PTR");
	opcodes_str[JIT_BOX_O] = CH("JIT_BOX_O");
	//opcodes_str[JIT_BOX_TRANSPTR] = CH("JIT_BOX_TRANSPTR");
	opcodes_str[JIT_BOX_F64] = CH("JIT_BOX_F64");
	opcodes_str[JIT_BOX_VALUETYPE] = CH("JIT_BOX_VALUETYPE");

	opcodes_str[JIT_CEQ_I32I32] = CH("JIT_CEQ_I32I32");
	opcodes_str[JIT_CGT_I32I32] = CH("JIT_CGT_I32I32");
	opcodes_str[JIT_CGT_UN_I32I32] = CH("JIT_CGT_UN_I32I32");
	opcodes_str[JIT_CLT_I32I32] = CH("JIT_CLT_I32I32");
	opcodes_str[JIT_CLT_UN_I32I32] = CH("JIT_CLT_UN_I32I32");
	opcodes_str[JIT_CEQ_I64I64] = CH("JIT_CEQ_I64I64");
	opcodes_str[JIT_CGT_I64I64] = CH("JIT_CGT_I64I64");
	opcodes_str[JIT_CGT_UN_I64I64] = CH("JIT_CGT_UN_I64I64");
	opcodes_str[JIT_CLT_I64I64] = CH("JIT_CLT_I64I64");
	opcodes_str[JIT_CLT_UN_I64I64] = CH("JIT_CLT_UN_I64I64");

	opcodes_str[JIT_ADD_OVF_I32I32] = CH("JIT_ADD_OVF_I32I32");
	opcodes_str[JIT_ADD_OVF_UN_I32I32] = CH("JIT_ADD_OVF_UN_I32I32");
	opcodes_str[JIT_MUL_OVF_I32I32] = CH("JIT_MUL_OVF_I32I32");
	opcodes_str[JIT_MUL_OVF_UN_I32I32] = CH("JIT_MUL_OVF_UN_I32I32");
	opcodes_str[JIT_SUB_OVF_I32I32] = CH("JIT_SUB_OVF_I32I32");
	opcodes_str[JIT_SUB_OVF_UN_I32I32] = CH("JIT_SUB_OVF_UN_I32I32");
	opcodes_str[JIT_ADD_I32I32] = CH("JIT_ADD_I32I32");
	opcodes_str[JIT_SUB_I32I32] = CH("JIT_SUB_I32I32");
	opcodes_str[JIT_MUL_I32I32] = CH("JIT_MUL_I32I32");
	opcodes_str[JIT_DIV_I32I32] = CH("JIT_DIV_I32I32");
	opcodes_str[JIT_DIV_UN_I32I32] = CH("JIT_DIV_UN_I32I32");
	opcodes_str[JIT_REM_I32I32] = CH("JIT_REM_I32I32");
	opcodes_str[JIT_REM_UN_I32I32] = CH("JIT_REM_UN_I32I32");
	opcodes_str[JIT_AND_I32I32] = CH("JIT_AND_I32I32");
	opcodes_str[JIT_OR_I32I32] = CH("JIT_OR_I32I32");
	opcodes_str[JIT_XOR_I32I32] = CH("JIT_XOR_I32I32");

	opcodes_str[JIT_NEG_I32] = CH("JIT_NEG_I32");
	opcodes_str[JIT_NOT_I32] = CH("JIT_NOT_I32");
	opcodes_str[JIT_NEG_I64] = CH("JIT_NEG_I64");
	opcodes_str[JIT_NOT_I64] = CH("JIT_NOT_I64");

	opcodes_str[JIT_BOX_NULLABLE] = CH("JIT_BOX_NULLABLE");
	opcodes_str[JIT_LOAD_F64] = CH("JIT_LOAD_F64");

	opcodes_str[JIT_BEQ_I32I32] = CH("JIT_BEQ_I32I32");
	opcodes_str[JIT_BGE_I32I32] = CH("JIT_BGE_I32I32");
	opcodes_str[JIT_BGT_I32I32] = CH("JIT_BGT_I32I32");
	opcodes_str[JIT_BLE_I32I32] = CH("JIT_BLE_I32I32");
	opcodes_str[JIT_BLT_I32I32] = CH("JIT_BLT_I32I32");
	opcodes_str[JIT_BNE_UN_I32I32] = CH("JIT_BNE_UN_I32I32");
	opcodes_str[JIT_BGE_UN_I32I32] = CH("JIT_BGE_UN_I32I32");
	opcodes_str[JIT_BGT_UN_I32I32] = CH("JIT_BGT_UN_I32I32");
	opcodes_str[JIT_BLE_UN_I32I32] = CH("JIT_BLE_UN_I32I32");
	opcodes_str[JIT_BLT_UN_I32I32] = CH("JIT_BLT_UN_I32I32");

	opcodes_str[JIT_BEQ_I64I64] = CH("JIT_BEQ_I64I64");
	opcodes_str[JIT_BGE_I64I64] = CH("JIT_BGE_I64I64");
	opcodes_str[JIT_BGT_I64I64] = CH("JIT_BGT_I64I64");
	opcodes_str[JIT_BLE_I64I64] = CH("JIT_BLE_I64I64");
	opcodes_str[JIT_BLT_I64I64] = CH("JIT_BLT_I64I64");
	opcodes_str[JIT_BNE_UN_I64I64] = CH("JIT_BNE_UN_I64I64");
	opcodes_str[JIT_BGE_UN_I64I64] = CH("JIT_BGE_UN_I64I64");
	opcodes_str[JIT_BGT_UN_I64I64] = CH("JIT_BGT_UN_I64I64");
	opcodes_str[JIT_BLE_UN_I64I64] = CH("JIT_BLE_UN_I64I64");
	opcodes_str[JIT_BLT_UN_I64I64] = CH("JIT_BLT_UN_I64I64");

	opcodes_str[JIT_SHL_I32] = CH("JIT_SHL_I32");
	opcodes_str[JIT_SHR_I32] = CH("JIT_SHR_I32");
	opcodes_str[JIT_SHR_UN_I32] = CH("JIT_SHR_UN_I32");
	opcodes_str[JIT_SHL_I64] = CH("JIT_SHL_I64");
	opcodes_str[JIT_SHR_I64] = CH("JIT_SHR_I64");
	opcodes_str[JIT_SHR_UN_I64] = CH("JIT_SHR_UN_I64");

	opcodes_str[JIT_BRANCH_FALSE] = CH("JIT_BRANCH_FALSE");
	opcodes_str[JIT_BRANCH_TRUE] = CH("JIT_BRANCH_TRUE");

	opcodes_str[JIT_LOADTOKEN_BASE] = CH("JIT_LOADTOKEN_BASE");
	opcodes_str[JIT_LOADTOKEN_TYPE] = CH("JIT_LOADTOKEN_TYPE");
	opcodes_str[JIT_LOADTOKEN_METHOD] = CH("JIT_LOADTOKEN_METHOD");
	opcodes_str[JIT_LOADTOKEN_FIELD] = CH("JIT_LOADTOKEN_FIELD");

	opcodes_str[JIT_LOADINDIRECT_I8] = CH("JIT_LOADINDIRECT_I8");
	opcodes_str[JIT_LOADINDIRECT_U8] = CH("JIT_LOADINDIRECT_U8");
	opcodes_str[JIT_LOADINDIRECT_I16] = CH("JIT_LOADINDIRECT_I16");
	opcodes_str[JIT_LOADINDIRECT_U16] = CH("JIT_LOADINDIRECT_U16");
	opcodes_str[JIT_LOADINDIRECT_I32] = CH("JIT_LOADINDIRECT_I32");
	opcodes_str[JIT_LOADINDIRECT_U32] = CH("JIT_LOADINDIRECT_U32");
	opcodes_str[JIT_LOADINDIRECT_I64] = CH("JIT_LOADINDIRECT_I64");
	opcodes_str[JIT_LOADINDIRECT_I] = CH("JIT_LOADINDIRECT_I");
	opcodes_str[JIT_LOADINDIRECT_R32] = CH("JIT_LOADINDIRECT_R32");
	opcodes_str[JIT_LOADINDIRECT_R64] = CH("JIT_LOADINDIRECT_R64");
	opcodes_str[JIT_LOADINDIRECT_REF] = CH("JIT_LOADINDIRECT_REF");

	opcodes_str[JIT_STOREINDIRECT_REF] = CH("JIT_STOREINDIRECT_REF");
	opcodes_str[JIT_STOREINDIRECT_U8] = CH("JIT_STOREINDIRECT_U8");
	opcodes_str[JIT_STOREINDIRECT_U16] = CH("JIT_STOREINDIRECT_U16");
	opcodes_str[JIT_STOREINDIRECT_U32] = CH("JIT_STOREINDIRECT_U32");
	opcodes_str[JIT_STOREINDIRECT_U64] = CH("JIT_STOREINDIRECT_U64");
	opcodes_str[JIT_STOREINDIRECT_R32] = CH("JIT_STOREINDIRECT_R32");
	opcodes_str[JIT_STOREINDIRECT_R64] = CH("JIT_STOREINDIRECT_R64");

opcodes_str[JIT_UNBOX_NULLABLE] = CH("JIT_UNBOX_NULLABLE");

opcodes_str[JIT_STORE_ELEMENT_32] = CH("JIT_STORE_ELEMENT_32");
opcodes_str[JIT_STORE_ELEMENT_64] = CH("JIT_STORE_ELEMENT_64");

opcodes_str[JIT_LOAD_ELEMENT_I8] = CH("JIT_LOAD_ELEMENT_I8");
opcodes_str[JIT_LOAD_ELEMENT_U8] = CH("JIT_LOAD_ELEMENT_U8");
opcodes_str[JIT_LOAD_ELEMENT_I16] = CH("JIT_LOAD_ELEMENT_I16");
opcodes_str[JIT_LOAD_ELEMENT_U16] = CH("JIT_LOAD_ELEMENT_U16");
opcodes_str[JIT_LOAD_ELEMENT_I32] = CH("JIT_LOAD_ELEMENT_I32");
opcodes_str[JIT_LOAD_ELEMENT_U32] = CH("JIT_LOAD_ELEMENT_U32");
opcodes_str[JIT_LOAD_ELEMENT_I64] = CH("JIT_LOAD_ELEMENT_I64");
opcodes_str[JIT_LOAD_ELEMENT_R32] = CH("JIT_LOAD_ELEMENT_R32");
opcodes_str[JIT_LOAD_ELEMENT_R64] = CH("JIT_LOAD_ELEMENT_R64");

opcodes_str[JIT_ADD_OVF_I64I64] = CH("JIT_ADD_OVF_I64I64");
opcodes_str[JIT_ADD_OVF_UN_I64I64] = CH("JIT_ADD_OVF_UN_I64I64");
opcodes_str[JIT_MUL_OVF_I64I64] = CH("JIT_MUL_OVF_I64I64");
opcodes_str[JIT_MUL_OVF_UN_I64I64] = CH("JIT_MUL_OVF_UN_I64I64");
opcodes_str[JIT_SUB_OVF_I64I64] = CH("JIT_SUB_OVF_I64I64");
opcodes_str[JIT_SUB_OVF_UN_I64I64] = CH("JIT_SUB_OVF_UN_I64I64");
opcodes_str[JIT_ADD_I64I64] = CH("JIT_ADD_I64I64");
opcodes_str[JIT_SUB_I64I64] = CH("JIT_SUB_I64I64");
opcodes_str[JIT_MUL_I64I64] = CH("JIT_MUL_I64I64");
opcodes_str[JIT_DIV_I64I64] = CH("JIT_DIV_I64I64");
opcodes_str[JIT_DIV_UN_I64I64] = CH("JIT_DIV_UN_I64I64");
opcodes_str[JIT_REM_I64I64] = CH("JIT_REM_I64I64");
opcodes_str[JIT_REM_UN_I64I64] = CH("JIT_REM_UN_I64I64");
opcodes_str[JIT_AND_I64I64] = CH("JIT_AND_I64I64");
opcodes_str[JIT_OR_I64I64] = CH("JIT_OR_I64I64");
opcodes_str[JIT_XOR_I64I64] = CH("JIT_XOR_I64I64");
opcodes_str[JIT_CEQ_F32F32] = CH("JIT_CEQ_F32F32");
opcodes_str[JIT_CGT_F32F32] = CH("JIT_CGT_F32F32");
opcodes_str[JIT_CGT_UN_F32F32] = CH("JIT_CGT_UN_F32F32");
opcodes_str[JIT_CLT_F32F32] = CH("JIT_CLT_F32F32");
opcodes_str[JIT_CLT_UN_F32F32] = CH("JIT_CLT_UN_F32F32");
opcodes_str[JIT_BEQ_F32F32] = CH("JIT_BEQ_F32F32");
opcodes_str[JIT_BGE_F32F32] = CH("JIT_BGE_F32F32");
opcodes_str[JIT_BGT_F32F32] = CH("JIT_BGT_F32F32");
opcodes_str[JIT_BLE_F32F32] = CH("JIT_BLE_F32F32");
opcodes_str[JIT_BLT_F32F32] = CH("JIT_BLT_F32F32");
opcodes_str[JIT_BNE_UN_F32F32] = CH("JIT_BNE_UN_F32F32");
opcodes_str[JIT_BGE_UN_F32F32] = CH("JIT_BGE_UN_F32F32");
opcodes_str[JIT_BGT_UN_F32F32] = CH("JIT_BGT_UN_F32F32");
opcodes_str[JIT_BLE_UN_F32F32] = CH("JIT_BLE_UN_F32F32");
opcodes_str[JIT_BLT_UN_F32F32] = CH("JIT_BLT_UN_F32F32");

opcodes_str[JIT_ADD_F32F32] = CH("JIT_ADD_F32F32");
opcodes_str[JIT_SUB_F32F32] = CH("JIT_SUB_F32F32");
opcodes_str[JIT_MUL_F32F32] = CH("JIT_MUL_F32F32");
opcodes_str[JIT_DIV_F32F32] = CH("JIT_DIV_F32F32");
opcodes_str[JIT_DIV_UN_F32F32] = CH("JIT_DIV_UN_F32F32"); // Never used
opcodes_str[JIT_REM_F32F32] = CH("JIT_REM_F32F32");
opcodes_str[JIT_REM_UN_F32F32] = CH("JIT_REM_UN_F32F32"); // Never used

opcodes_str[JIT_CEQ_F64F64] = CH("JIT_CEQ_F64F64");
opcodes_str[JIT_CGT_F64F64] = CH("JIT_CGT_F64F64");
opcodes_str[JIT_CGT_UN_F64F64] = CH("JIT_CGT_UN_F64F64");
opcodes_str[JIT_CLT_F64F64] = CH("JIT_CLT_F64F64");
opcodes_str[JIT_CLT_UN_F64F64] = CH("JIT_CLT_UN_F64F64");

opcodes_str[JIT_BEQ_F64F64] = CH("JIT_BEQ_F64F64");
opcodes_str[JIT_BGE_F64F64] = CH("JIT_BGE_F64F64");
opcodes_str[JIT_BGT_F64F64] = CH("JIT_BGT_F64F64");
opcodes_str[JIT_BLE_F64F64] = CH("JIT_BLE_F64F64");
opcodes_str[JIT_BLT_F64F64] = CH("JIT_BLT_F64F64");
opcodes_str[JIT_BNE_UN_F64F64] = CH("JIT_BNE_UN_F64F64");
opcodes_str[JIT_BGE_UN_F64F64] = CH("JIT_BGE_UN_F64F64");
opcodes_str[JIT_BGT_UN_F64F64] = CH("JIT_BGT_UN_F64F64");
opcodes_str[JIT_BLE_UN_F64F64] = CH("JIT_BLE_UN_F64F64");
opcodes_str[JIT_BLT_UN_F64F64] = CH("JIT_BLT_UN_F64F64");

opcodes_str[JIT_ADD_F64F64] = CH("JIT_ADD_F64F64");
opcodes_str[JIT_SUB_F64F64] = CH("JIT_SUB_F64F64");
opcodes_str[JIT_MUL_F64F64] = CH("JIT_MUL_F64F64");
opcodes_str[JIT_DIV_F64F64] = CH("JIT_DIV_F64F64");
opcodes_str[JIT_DIV_UN_F64F64] = CH(""); // Never used
opcodes_str[JIT_REM_F64F64] = CH("JIT_REM_F64F64");
opcodes_str[JIT_REM_UN_F64F64] = CH("JIT_REM_UN_F64F64"); // Never used

opcodes_str[JIT_LOADPARAMLOCAL_0] = CH("JIT_LOADPARAMLOCAL_0"); // Load 4-byte param/local at offset 0
opcodes_str[JIT_LOADPARAMLOCAL_1] = CH("JIT_LOADPARAMLOCAL_1"); // Load 4-byte param/local at offset 4
opcodes_str[JIT_LOADPARAMLOCAL_2] = CH("JIT_LOADPARAMLOCAL_2"); // Load 4-byte param/local at offset 8
opcodes_str[JIT_LOADPARAMLOCAL_3] = CH("JIT_LOADPARAMLOCAL_3"); // Load 4-byte param/local at offset 12
opcodes_str[JIT_LOADPARAMLOCAL_4] = CH("JIT_LOADPARAMLOCAL_4"); // Load 4-byte param/local at offset 16
opcodes_str[JIT_LOADPARAMLOCAL_5] = CH("JIT_LOADPARAMLOCAL_5"); // Load 4-byte param/local at offset 20
opcodes_str[JIT_LOADPARAMLOCAL_6] = CH("JIT_LOADPARAMLOCAL_6"); // Load 4-byte param/local at offset 24
opcodes_str[JIT_LOADPARAMLOCAL_7] = CH("JIT_LOADPARAMLOCAL_7"); // Load 4-byte param/local at offset 28

opcodes_str[JIT_STOREPARAMLOCAL_0] = CH("JIT_STOREPARAMLOCAL_0"); // Store 4-byte param/local at offset 0
opcodes_str[JIT_STOREPARAMLOCAL_1] = CH("JIT_STOREPARAMLOCAL_1"); // Store 4-byte param/local at offset 4
opcodes_str[JIT_STOREPARAMLOCAL_2] = CH("JIT_STOREPARAMLOCAL_2"); // Store 4-byte param/local at offset 8
opcodes_str[JIT_STOREPARAMLOCAL_3] = CH("JIT_STOREPARAMLOCAL_3"); // Store 4-byte param/local at offset 12
opcodes_str[JIT_STOREPARAMLOCAL_4] = CH("JIT_STOREPARAMLOCAL_4"); // Store 4-byte param/local at offset 16
opcodes_str[JIT_STOREPARAMLOCAL_5] = CH("JIT_STOREPARAMLOCAL_5"); // Store 4-byte param/local at offset 20
opcodes_str[JIT_STOREPARAMLOCAL_6] = CH("JIT_STOREPARAMLOCAL_6"); // Store 4-byte param/local at offset 24
opcodes_str[JIT_STOREPARAMLOCAL_7] = CH("JIT_STOREPARAMLOCAL_7"); // Store 4-byte param/local at offset 28

opcodes_str[JIT_LOAD_I4_M1] = CH("JIT_LOAD_I4_M1");
opcodes_str[JIT_LOAD_I4_0] = CH("JIT_LOAD_I4_0");
opcodes_str[JIT_LOAD_I4_1] = CH("JIT_LOAD_I4_1");
opcodes_str[JIT_LOAD_I4_2] = CH("JIT_LOAD_I4_2");

opcodes_str[JIT_LOADFIELD_4] = CH("JIT_LOADFIELD_4");

/*
opcodes_str[JIT_CONV_OFFSET_I32] = CH("JIT_CONV_OFFSET_I32");
opcodes_str[JIT_CONV_OFFSET_U32] = CH("JIT_CONV_OFFSET_U32");
opcodes_str[JIT_CONV_OFFSET_I64] = CH("JIT_CONV_OFFSET_I64");
opcodes_str[JIT_CONV_OFFSET_U64] = CH("JIT_CONV_OFFSET_U64");
opcodes_str[JIT_CONV_OFFSET_R32] = CH("JIT_CONV_OFFSET_R32");
opcodes_str[JIT_CONV_OFFSET_R64] = CH("JIT_CONV_OFFSET_R64");
*/

opcodes_str[JIT_CONV_FROM_I32] = CH("JIT_CONV_FROM_I32");
opcodes_str[JIT_CONV_I32_I32] = CH("JIT_CONV_I32_I32");
opcodes_str[JIT_CONV_I32_U32] = CH("JIT_CONV_I32_U32");
opcodes_str[JIT_CONV_I32_I64] = CH("JIT_CONV_I32_I64");
opcodes_str[JIT_CONV_I32_U64] = CH("JIT_CONV_I32_U64");
opcodes_str[JIT_CONV_I32_R32] = CH("JIT_CONV_I32_R32");
opcodes_str[JIT_CONV_I32_R64] = CH("JIT_CONV_I32_R64");

opcodes_str[JIT_CONV_FROM_U32] = CH("JIT_CONV_FROM_U32");
opcodes_str[JIT_CONV_U32_I32] = CH("JIT_CONV_U32_I32");
opcodes_str[JIT_CONV_U32_U32] = CH("JIT_CONV_U32_U32");
opcodes_str[JIT_CONV_U32_I64] = CH("JIT_CONV_U32_I64");
opcodes_str[JIT_CONV_U32_U64] = CH("JIT_CONV_U32_U64");
opcodes_str[JIT_CONV_U32_R32] = CH("JIT_CONV_U32_R32");
opcodes_str[JIT_CONV_U32_R64] = CH("JIT_CONV_U32_R64");

opcodes_str[JIT_CONV_FROM_I64] = CH("JIT_CONV_FROM_I64");
opcodes_str[JIT_CONV_I64_I32] = CH("JIT_CONV_I64_I32");
opcodes_str[JIT_CONV_I64_U32] = CH("JIT_CONV_I64_U32");
opcodes_str[JIT_CONV_I64_I64] = CH("JIT_CONV_I64_I64"); // Not used
opcodes_str[JIT_CONV_I64_U64] = CH("JIT_CONV_I64_U64"); // Not used
opcodes_str[JIT_CONV_I64_R32] = CH("JIT_CONV_I64_R32");
opcodes_str[JIT_CONV_I64_R64] = CH("JIT_CONV_I64_R64");
opcodes_str[JIT_CONV_FROM_U64] = CH("JIT_CONV_FROM_U64");
opcodes_str[JIT_CONV_U64_I32] = CH("JIT_CONV_U64_I32");
opcodes_str[JIT_CONV_U64_U32] = CH("JIT_CONV_U64_U32");
opcodes_str[JIT_CONV_U64_I64] = CH("JIT_CONV_U64_I64"); // Not used
opcodes_str[JIT_CONV_U64_U64] = CH("JIT_CONV_U64_U64"); // Not used
opcodes_str[JIT_CONV_U64_R32] = CH("JIT_CONV_U64_R32");
opcodes_str[JIT_CONV_U64_R64] = CH("JIT_CONV_U64_R64");

opcodes_str[JIT_CONV_FROM_R32] = CH("JIT_CONV_FROM_R32");
opcodes_str[JIT_CONV_R32_I32] = CH("JIT_CONV_R32_I32");
opcodes_str[JIT_CONV_R32_U32] = CH("JIT_CONV_R32_U32");
opcodes_str[JIT_CONV_R32_I64] = CH("JIT_CONV_R32_I64");
opcodes_str[JIT_CONV_R32_U64] = CH("JIT_CONV_R32_U64");
opcodes_str[JIT_CONV_R32_R32] = CH("JIT_CONV_R32_R32");
opcodes_str[JIT_CONV_R32_R64] = CH("JIT_CONV_R32_R64");

opcodes_str[JIT_CONV_FROM_R64] = CH("JIT_CONV_FROM_R64");
opcodes_str[JIT_CONV_R64_I32] = CH("JIT_CONV_R64_I32");
opcodes_str[JIT_CONV_R64_U32] = CH("JIT_CONV_R64_U32");
opcodes_str[JIT_CONV_R64_I64] = CH("JIT_CONV_R64_I64");
opcodes_str[JIT_CONV_R64_U64] = CH("JIT_CONV_R64_U64");
opcodes_str[JIT_CONV_R64_R32] = CH("JIT_CONV_R64_R32");
opcodes_str[JIT_CONV_R64_R64] = CH("JIT_CONV_R64_R64");

}

const char * get_str_opcode(int opcode)
{
	if (is_init == 0)
	{
		init_str_opcodes();
		is_init = 1;
	}

	if (opcode < 0 || opcode > JIT_CONV_R64_R64)
	{
		return "";
	}

	if (opcodes_str[opcode] == 0)
	{
		return "";
	}

	return opcodes_str[opcode];
}